services:
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    # If your frontend makes API requests to 0.0.0.0:8000, it won't resolve from the host machine,
    # so you might define an environment variable for the backend URL or handle proxying.

  backend:
    build: ./apps/backend
    ports:
      - "8000:8000"
    # If you use a .env or DB, volume them or pass ENV variables here
